In [3]:
import numpy as np
import pandas as pd

In [6]:
df_boe_23 = pd.read_csv('../data/bronze/boe_2023.csv')
display(df_boe_23.head())

,identificador,titulo,url_html,pdf_link,seccion,departamento,site,place,date,year,month,day
0,BOE-A-2023-1,"Resolución de 23 de diciembre de 2022, de la S...",https://www.boe.es/diario_boe/txt.php?id=BOE-A...,https://www.boe.es/boe/dias/2023/01/02/pdfs/BO...,II. Autoridades y personal. - A. Nombramientos...,"MINISTERIO DE ASUNTOS EXTERIORES, UNIÓN EUROPE...",boe,espana,2023/01/02,2023,1,2
1,BOE-A-2023-2,"Resolución de 27 de diciembre de 2022, de la S...",https://www.boe.es/diario_boe/txt.php?id=BOE-A...,https://www.boe.es/boe/dias/2023/01/02/pdfs/BO...,II. Autoridades y personal. - A. Nombramientos...,"MINISTERIO DE TRANSPORTES, MOVILIDAD Y AGENDA ...",boe,espana,2023/01/02,2023,1,2
2,BOE-A-2023-3,"Resolución de 21 de diciembre de 2022, de las ...",https://www.boe.es/diario_boe/txt.php?id=BOE-A...,https://www.boe.es/boe/dias/2023/01/02/pdfs/BO...,II. Autoridades y personal. - A. Nombramientos...,MINISTERIO DE TRABAJO Y ECONOMÍA SOCIAL,boe,espana,2023/01/02,2023,1,2
3,BOE-A-2023-4,"Resolución de 29 de diciembre de 2022, de la S...",https://www.boe.es/diario_boe/txt.php?id=BOE-A...,https://www.boe.es/boe/dias/2023/01/02/pdfs/BO...,II. Autoridades y personal. - A. Nombramientos...,"MINISTERIO DE LA PRESIDENCIA, RELACIONES CON L...",boe,espana,2023/01/02,2023,1,2
4,BOE-A-2023-5,"Resolución de 21 de diciembre de 2022, de la S...",https://www.boe.es/diario_boe/txt.php?id=BOE-A...,https://www.boe.es/boe/dias/2023/01/02/pdfs/BO...,II. Autoridades y personal. - A. Nombramientos...,"MINISTERIO DE INCLUSIÓN, SEGURIDAD SOCIAL Y MI...",boe,espana,2023/01/02,2023,1,2

# Cotrol de calidad básico

In [21]:
df_boe_23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65818 entries, 0 to 65817
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   identificador  65818 non-null  object
 1   titulo         65818 non-null  object
 2   url_html       65818 non-null  object
 3   pdf_link       65818 non-null  object
 4   seccion        65818 non-null  object
 5   departamento   65818 non-null  object
 6   site           65818 non-null  object
 7   place          65818 non-null  object
 8   date           65818 non-null  object
 9   year           65818 non-null  int64
 10  month          65818 non-null  int64
 11  day            65818 non-null  int64
dtypes: int64(3), object(9)
memory usage: 6.0+ MB

In [23]:
# Identificador es efectivamente un campo único, no hay duplicados.
df_boe_23.nunique()

identificador    65818
titulo           44163
url_html         65818
pdf_link         65818
seccion              9
departamento        89
site                 1
place                1
date               311
year                 1
month               12
day                 31
dtype: int64

In [ ]:
(
    df_boe_23[df_boe_23
           .duplicated(subset=["titulo"], keep=False)]
           .sort_values("titulo")
)

,identificador,titulo,url_html,pdf_link,seccion,departamento,site,place,date,year,month,day
44287,BOE-B-2023-25612,A ORTIGUEIRA,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/09/09/pdfs/BO...,IV. Administración de Justicia,JUZGADOS DE PRIMERA INSTANCIA E INSTRUCCIÓN,boe,espana,2023/09/09,2023,9,9
54129,BOE-B-2023-32052,A ORTIGUEIRA,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/11/04/pdfs/BO...,IV. Administración de Justicia,JUZGADOS DE PRIMERA INSTANCIA E INSTRUCCIÓN,boe,espana,2023/11/04,2023,11,4
3522,BOE-B-2023-1660,A ORTIGUEIRA,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/01/21/pdfs/BO...,IV. Administración de Justicia,JUZGADOS DE PRIMERA INSTANCIA E INSTRUCCIÓN,boe,espana,2023/01/21,2023,1,21
32942,BOE-B-2023-18778,A ORTIGUEIRA,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/06/20/pdfs/BO...,IV. Administración de Justicia,JUZGADOS DE PRIMERA INSTANCIA E INSTRUCCIÓN,boe,espana,2023/06/20,2023,6,20
45817,BOE-B-2023-26675,A ORTIGUEIRA,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/09/18/pdfs/BO...,IV. Administración de Justicia,JUZGADOS DE PRIMERA INSTANCIA E INSTRUCCIÓN,boe,espana,2023/09/18,2023,9,18
...,...,...,...,...,...,...,...,...,...,...,...,...
2377,BOE-B-2023-1294,ZONA RECADACIÓN PONTEVEDRA - AXENCIA TRIBUTARI...,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/01/16/pdfs/BO...,V. Anuncios. - B. Otros anuncios oficiales,COMUNIDAD AUTÓNOMA DE GALICIA,boe,espana,2023/01/16,2023,1,16
8373,BOE-B-2023-4534,ZONA RECADACIÓN PONTEVEDRA - AXENCIA TRIBUTARI...,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/02/13/pdfs/BO...,V. Anuncios. - B. Otros anuncios oficiales,COMUNIDAD AUTÓNOMA DE GALICIA,boe,espana,2023/02/13,2023,2,13
12241,BOE-B-2023-6493,ZONA RECADACIÓN PONTEVEDRA - AXENCIA TRIBUTARI...,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/03/04/pdfs/BO...,V. Anuncios. - B. Otros anuncios oficiales,COMUNIDAD AUTÓNOMA DE GALICIA,boe,espana,2023/03/04,2023,3,4
49297,BOE-B-2023-29021,ZONA RECADACIÓN VIGO - AXENCIA TRIBUTARIA DE G...,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/10/07/pdfs/BO...,V. Anuncios. - B. Otros anuncios oficiales,COMUNIDAD AUTÓNOMA DE GALICIA,boe,espana,2023/10/07,2023,10,7
49298,BOE-B-2023-29022,ZONA RECADACIÓN VIGO - AXENCIA TRIBUTARIA DE G...,https://www.boe.es/diario_boe/txt.php?id=BOE-B...,https://www.boe.es/boe/dias/2023/10/07/pdfs/BO...,V. Anuncios. - B. Otros anuncios oficiales,COMUNIDAD AUTÓNOMA DE GALICIA,boe,espana,2023/10/07,2023,10,7

In [82]:
titulos_repetidos = (
    df_boe_23
    .groupby("titulo", as_index=False)
    .size()
    .rename(columns={"size": "num_registros"})
    .query("num_registros > 1")
    .sort_values("titulo")
)

# titulos_repetidos = (
#     df_boe_23
#     .assign(num_registros=df_boe_23.groupby("titulo")["titulo"].transform("size"))  # Añade una columna 'num_registros' con el número de veces que aparece cada título
#     .loc[lambda df: df["num_registros"] > 1, ["identificador", "titulo", "url_html", "num_registros"]]  # Conserva únicamente las filas cuyo título aparece más de una vez y selecciona las columnas de interés
#     .sort_values(["titulo", "url_html"])  # Ordena el resultado por título y URL para facilitar la revisión
# )

titulos_repetidos

                                                  titulo  num_registros
2                                           A ORTIGUEIRA             10
11     AGENCIA MUNICIPAL TRIBUTARIA DEL AYUNTAMIENTO ...              6
12     AGENCIA PÚBLICA DE SERVICIOS ECONÓMICOS PROVIN...             26
13                            AGENCIA TRIBUTARIA CANARIA             28
14                       AGENCIA TRIBUTARIA DE ANDALUCÍA              6
...                                                  ...            ...
44158                                             ZAMORA             22
44159                                           ZARAGOZA            220
44160  ZONA RECADACIÓN CORUÑA - AXENCIA TRIBUTARIA DE...              3
44161  ZONA RECADACIÓN PONTEVEDRA - AXENCIA TRIBUTARI...              7
44162  ZONA RECADACIÓN VIGO - AXENCIA TRIBUTARIA DE G...              2

[2383 rows x 2 columns]

In [40]:
# Comprobar que no hay valores nulos.
print(df_boe_23["url_html"].isna().sum())
print(df_boe_23["pdf_link"].isna().sum())

0
0

In [35]:
# Comprobar que comienzadn por https.
print(df_boe_23["url_html"].str.startswith("https://").value_counts())
print(df_boe_23["pdf_link"].str.startswith("https://").value_counts())

url_html
True    65818
Name: count, dtype: int64
pdf_link
True    65818
Name: count, dtype: int64

In [38]:
# Comprobar que no hay duplicados.
print(df_boe_23["url_html"].duplicated().sum())
print(df_boe_23["pdf_link"].duplicated().sum())

0
0

# Filtrado temático

Dado que la base de datos inicial contiene la totalidad de disposiciones publicadas en el BOE durante el período analizado, la validación exhaustiva de accesibilidad de los enlaces HTML y PDF se realizó únicamente sobre el subconjunto de registros previamente identificado como potencialmente relacionado con proyectos de energías renovables. Esta decisión permitió optimizar los recursos computacionales sin afectar a la calidad del conjunto de datos final objeto de estudio.

In [ ]:
# Crear una versión normalizada del título. Se aborda mayúsculas/miúsculas, tildes y caracteres especiales.
df_boe_23["titulo_norm"] = (
    df_boe_23["titulo"]
    .str.lower()
    .str.normalize("NFKD")  # Descompone caracteres acentuados (á → a + acento, ñ → n + tilde, etc.)
    .str.encode("ascii", errors="ignore")  # Convierte a ASCII eliminando los caracteres no representables (acentos, diéresis, etc.)
    .str.decode("utf-8")  # Convierte de nuevo los bytes ASCII a texto UTF-8
)

df_boe_23

In [95]:
keywords_energy = [
    "parque eolico",
    "parque solar",
    "planta fotovoltaica",
    "instalacion fotovoltaica",
    "instalacion solar",
    "energia eolica",
    "energia solar",
    "subestacion electrica",
    "linea electrica",
    "linea de evacuacion",
    "evacuacion de energia",
    "alta tension",
    "muy alta tension",
    "generacion electrica"
]

keywords_permitting = [
    "autorizacion administrativa previa",
    "autorizacion administrativa de construccion",
    "declaracion de impacto ambiental",
    "evaluacion de impacto ambiental",
    "informacion publica",
    "utilidad publica",
    "ocupacion de bienes",
    "expropiacion forzosa"
]

# Unifica todas las palabras clave eliminando duplicados
keywords = sorted(set(keywords_energy + keywords_permitting))

# Construye la expresión regular
regex = "|".join(keywords)

# Filtra los registros candidatos
df_energia_23 = df_boe_23[
    df_boe_23["titulo_norm"].str.contains(regex, na=False)
]

In [109]:
df_energia_23.head(2)

,identificador,titulo,url_html,pdf_link,seccion,departamento,site,place,date,year,month,day,titulo_norm
48,BOE-A-2023-49,"Resolución de 22 de diciembre de 2022, de la D...",https://www.boe.es/diario_boe/txt.php?id=BOE-A...,https://www.boe.es/boe/dias/2023/01/02/pdfs/BO...,III. Otras disposiciones,MINISTERIO PARA LA TRANSICIÓN ECOLÓGICA Y EL R...,boe,espana,2023/01/02,2023,1,2,"resolucion de 22 de diciembre de 2022, de la d..."
49,BOE-A-2023-50,"Resolución de 23 de diciembre de 2022, de la D...",https://www.boe.es/diario_boe/txt.php?id=BOE-A...,https://www.boe.es/boe/dias/2023/01/02/pdfs/BO...,III. Otras disposiciones,MINISTERIO PARA LA TRANSICIÓN ECOLÓGICA Y EL R...,boe,espana,2023/01/02,2023,1,2,"resolucion de 23 de diciembre de 2022, de la d..."

In [112]:
df_energia_23.loc[df_energia_23["identificador"] == "BOE-A-2023-50", "url_html"].iloc[0]

'https://www.boe.es/diario_boe/txt.php?id=BOE-A-2023-50'

In [ ]:
# Dos fases

test_abedul = df_boe_23[
    df_boe_23["titulo_norm"].str.contains('abedul ii', na=False)
]

for row in test_abedul.itertuples():
    print(f"Identificador: {row.identificador}")
    print(f"Título: {row.titulo}")

Identificador: BOE-A-2023-50
Título: Resolución de 23 de diciembre de 2022, de la Dirección General de Calidad y Evaluación Ambiental, por la que se formula declaración de impacto ambiental del proyecto "Instalación fotovoltaica Abedul II New Energy, de 53 MWp, y su infraestructura de evacuación en Alfajarín (Zaragoza)".
Identificador: BOE-A-2023-13064
Título: Resolución de 25 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enebro New Energy, SL, autorización administrativa previa para la instalación fotovoltaica Abedul II New Energy, de 53 MW de potencia pico y 51,55 MW de potencia instalada, y su infraestructura de evacuación, en Alfajarín (Zaragoza).

In [ ]:
# Tres fases

test_barqueiro = df_boe_23[
    df_boe_23["titulo_norm"].str.contains('parque eolico barqueiro', na=False)
]

for row in test_barqueiro.itertuples():
    print(f"Identificador: {row.identificador}")
    print(f"Título: {row.titulo}")

Identificador: BOE-A-2023-2921
Título: Resolución de 23 de enero de 2023, de la Dirección General de Calidad y Evaluación Ambiental, por la que se formula declaración de impacto ambiental del proyecto "Parque eólico Barqueiro de 150 MW, y de su infraestructura de evacuación asociada, en los términos municipales de As Pontes de García Rodríguez, As Somozas, Cerdido, Mañón, Moeche y Ortigueira (A Coruña) y O Vicedo (Lugo)."
Identificador: BOE-A-2023-13045
Título: Resolución de 21 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para el parque eólico Barqueiro, de 126 MW, y sus infraestructuras de evacuación, ubicados en O Vicedo y Viveiro (Lugo) y Mañón, Ortigueira, Cerdido, Moeche, As Somozas y As Pontes (A Coruña).
Identificador: BOE-B-2023-17281
Título: Anuncio del Área Funcional de Industria y Energía de la Delegación del Gobierno en Galicia por el que se somete a Información Pública la modificación de la Autorización Administrativa Previa (AAP) y la solicitud de la Autorización Administrativa de Construcción (ACC) del PROYECTO MODIFICADO mayo 2023 de la instalación «Parque Eólico Barqueiro», de 126 MW de potencia instalada, sus accesos y su infraestructura de evacuación, en los términos municipales de Ortigueira, Mañón y Cerdido, en la provincia de A Coruña, promovido por la mercantil «ENEL GREEN POWER ESPAÑA, S.L. (unipersonal)». CÓDIGO PEol-414 .

In [ ]:
# Expropiación forzosa
test_revuelta = df_boe_23[
    df_boe_23["titulo_norm"].str.contains('planta solar fotovoltaica la revuelta', na=False)
]

for row in test_revuelta.itertuples():
    print(f"Identificador: {row.identificador}")
    print(f"Título: {row.titulo}")

Identificador: BOE-B-2023-9376
Título: Resolución de la Delegación del Gobierno en Castilla-La Mancha por la que se convoca el levantamiento de actas previas a la ocupación de determinadas fincas afectadas por la construcción de la "Planta Solar Fotovoltaica La Revuelta" de 126 MWp e infraestructuras de evacuación, promovida por la empresa ENEL GREEN POWER ESPAÑA, S.L.U., en el término municipal de Manzanares (Ciudad Real).

In [121]:
test_enel = df_boe_23[
    df_boe_23["titulo_norm"].str.contains('enel green', na=False)
]

for row in test_enel.itertuples():
    print(f"Identificador: {row.identificador}")
    print(f"Título: {row.titulo}")

Identificador: BOE-A-2023-49
Título: Resolución de 22 de diciembre de 2022, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa de construcción para el parque solar fotovoltaico Dulcinea de 84,216 MW de potencia instalada, la subestación eléctrica 30/220 kV, la línea a 220 kV, la subestación eléctrica 220/400 kV y la línea a 400 kV para la evacuación de energía eléctrica, en Carmona (Sevilla), y se declara, en concreto, la utilidad pública de las líneas eléctricas a 220 kV y 400 kV y la subestación eléctrica 220/400 kV.
Identificador: BOE-A-2023-3822
Título: Resolución de 30 de enero de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para la planta solar fotovoltaica Aljarafe, de 69,6 MW de potencia instalada, e infraestructuras de evacuación subestación "SET FV Aljarafe 30/220 kV" y línea eléctrica 220 kV "SET FV Aljarafe-SET Santiponce", en Salteras y Valencina de la Concepción (Sevilla).
Identificador: BOE-B-2023-9376
Título: Resolución de la Delegación del Gobierno en Castilla-La Mancha por la que se convoca el levantamiento de actas previas a la ocupación de determinadas fincas afectadas por la construcción de la "Planta Solar Fotovoltaica La Revuelta" de 126 MWp e infraestructuras de evacuación, promovida por la empresa ENEL GREEN POWER ESPAÑA, S.L.U., en el término municipal de Manzanares (Ciudad Real).
Identificador: BOE-A-2023-10305
Título: Resolución de 17 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para el parque eólico Moeche de 50,4 MW instalados, y sus infraestructuras de evacuación, ubicados en San Sadurniño, Moeche, As Somozas y As Pontes (A Coruña).
Identificador: BOE-A-2023-10306
Título: Resolución de 17 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para el parque eólico Badulaque de 90 MW, y sus infraestructuras de evacuación, ubicados en Valdoviño, Cerdido, Cedeira, Moeche, As Somozas y As Pontés (A Coruña).
Identificador: BOE-A-2023-10307
Título: Resolución de 17 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para el parque eólico Tesouro de 50,4 MW instalados, y sus infraestructuras de evacuación, ubicados en A Capela y As Pontes de García Rodríguez (A Coruña).
Identificador: BOE-A-2023-10308
Título: Resolución de 17 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para el parque eólico Santuario de 161 MW instalados, y sus infraestructuras de evacuación, ubicados en Xermade, Vilalba y Guitiriz (Lugo) y As Pontes de García Rodríguez (A Coruña).
Identificador: BOE-A-2023-10317
Título: Resolución de 17 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para la instalación fotovoltaica Balbona de 130,6 MW de potencia instalada, y su infraestructura de evacuación, en Jumilla (Murcia).
Identificador: BOE-A-2023-11003
Título: Resolución de 20 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, la autorización administrativa previa y la autorización administrativa de construcción para la instalación fotovoltaica "Centurión" de 116,5 MW de potencia instalada, y su infraestructura de evacuación, en Segura de León, Valencia del Ventoso, Fuente de Cantos y Fregenal de la Sierra (Badajoz) y se declara, en concreto, su utilidad pública.
Identificador: BOE-A-2023-11171
Título: Resolución de 20 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para la instalación "Villameca" de 195,999 MW de potencia pico, 158,629 MW de potencia instalada y sus infraestructuras de evacuación, en Quintana del Castillo (León).
Identificador: BOE-A-2023-11309
Título: Resolución de 20 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para la instalación fotovoltaica Campos de 70,4 MW de potencia instalada, y su infraestructura de evacuación asociada, en Mula y Campos del Río (Murcia).
Identificador: BOE-A-2023-12328
Título: Resolución de 25 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, la autorización administrativa previa para la planta fotovoltaica Carbo de 81,40 MW de potencia instalada, e infraestructura de evacuación a 30 kV, en Fuente Palmera, Guadalcázar y Almodóvar del Río (Córdoba).
Identificador: BOE-A-2023-13039
Título: Resolución de 20 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SLU, autorización administrativa previa para la instalación fotovoltaica Muel, de 199,97 MW de potencia pico y 179,6 MW de potencia instalada y sus infraestructuras de evacuación, en Muel, Zaragoza, La Muela y María de Huerva (Zaragoza).
Identificador: BOE-A-2023-13045
Título: Resolución de 21 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para el parque eólico Barqueiro, de 126 MW, y sus infraestructuras de evacuación, ubicados en O Vicedo y Viveiro (Lugo) y Mañón, Ortigueira, Cerdido, Moeche, As Somozas y As Pontes (A Coruña).
Identificador: BOE-A-2023-13052
Título: Resolución de 23 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SLU, autorización administrativa previa para la instalación fotovoltaica Alfajarín Solar, de 90 MW de potencia pico y 76,8 MW de potencia instalada y su infraestructura de evacuación, en Alfajarín (Zaragoza).
Identificador: BOE-A-2023-13055
Título: Resolución de 24 de abril de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para la instalación fotovoltaica Andrea, de 229,95 MW de potencia instalada y su infraestructura de evacuación, en Antas (Almería).
Identificador: BOE-A-2023-13070
Título: Resolución de 23 de mayo de 2023, de la Dirección General de Política Energética y Minas, por la que se corrigen errores en la de 17 de abril de 2023, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa para el parque eólico Tesouro de 50,4 MW instalados, y sus infraestructuras de evacuación, ubicados en A Capela y As Pontes de García Rodríguez (A Coruña).
Identificador: BOE-B-2023-16840
Título: Anuncio del Área de Industria y Energía de la Delegación del Gobierno en Galicia por el que se somete a Información Pública la modificación de la Autorización Administrativa Previa y la solicitud de la Autorización Administrativa de Construcción del PROYECTO MODIFICADO abril 2023 de la instalación «Parque Eólico Moeche", de 50,4 MW de potencia instalada, sus accesos y su infraestructura de evacuación, en la provincia de A Coruña, promovido por la mercantil «ENEL GREEN POWER ESPAÑA, S.L. (unipersonal)». CÓDIGO PEol-415 .
Identificador: BOE-B-2023-17281
Título: Anuncio del Área Funcional de Industria y Energía de la Delegación del Gobierno en Galicia por el que se somete a Información Pública la modificación de la Autorización Administrativa Previa (AAP) y la solicitud de la Autorización Administrativa de Construcción (ACC) del PROYECTO MODIFICADO mayo 2023 de la instalación «Parque Eólico Barqueiro», de 126 MW de potencia instalada, sus accesos y su infraestructura de evacuación, en los términos municipales de Ortigueira, Mañón y Cerdido, en la provincia de A Coruña, promovido por la mercantil «ENEL GREEN POWER ESPAÑA, S.L. (unipersonal)». CÓDIGO PEol-414 .
Identificador: BOE-B-2023-18602
Título: Anuncio del Área Funcional de Industria y Energía de la Delegación del Gobierno en Galicia por el que se somete a Información Pública la modificación de la Autorización Administrativa Previa (AAP) y la solicitud de la Autorización Administrativa de Construcción (AAC) del PROYECTO MODIFICADO abril 2023 de la instalación «Parque Eólico Santuario», de 161 MW de potencia instalada, sus accesos y su infraestructura de evacuación, en los términos municipales de Xermade, Vilalba y Guitiriz en la provincia de Lugo y As Pontes de García Rodríguez en la provincia de A Coruña, promovido por la mercantil «ENEL GREEN POWER ESPAÑA, S.L. (unipersonal)». CÓDIGO PEol-422 .
Identificador: BOE-B-2023-19082
Título: Anuncio del Área Funcional de Industria y Energía de la Delegación del Gobierno en Galicia por el que se somete a Información Pública la modificación de la Autorización Administrativa Previa (AAP) y la solicitud de la Autorización Administrativa de Construcción (AAC) del PROYECTO MODIFICADO mayo 2023 de la instalación «Parque Eólico Badulaque», de 102,4 MW de potencia instalada, sus accesos y su infraestructura de evacuación, en los términos municipales de Valdoviño, Cedeira, Cerdido, Moeche, As Somozas y As Pontes de García Rodríguez en la provincia de A Coruña, promovido por la mercantil «ENEL GREEN POWER ESPAÑA, S.L. (unipersonal)». CÓDIGO PEol-416 .
Identificador: BOE-B-2023-19563
Título: Resolución de la Dirección General de Energía de 22 de marzo de 2023, por la que se concede a Enel Green Power España, S.L. Autorización Administrativa y Declaración, en concreto, de Utilidad Pública, de la instalación eléctrica correspondiente al proyecto denominado "Parque Eólico Central Térmica de Granadilla 2xG145-5 MW", en el término municipal de Granadilla de Abona. Isla de Tenerife.- Expte. n.º ER100045.
Identificador: BOE-A-2023-17789
Título: Resolución de 18 de julio de 2023, de la Dirección General de Política Energética y Minas, por la que se desestima la solicitud de Enel Green Power España, SL, de autorización administrativa previa del parque eólico Molinaseca, de 60 MW de potencia instalada y de su infraestructura de evacuación, en la provincia de León.
Identificador: BOE-A-2023-17790
Título: Resolución de 18 de julio de 2023, de la Dirección General de Política Energética y Minas, por la que se desestima la solicitud de Enel Green Power España, SL, de autorización administrativa previa del parque eólico Busmayor, de 60 MW de potencia instalada y de su infraestructura de evacuación, en la provincia de León.
Identificador: BOE-A-2023-17793
Título: Resolución de 19 de julio de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa de construcción para la instalación fotovoltaica Aljarafe, de 74,825 MW de potencia instalada, e infraestructuras de evacuación subestación "SET FV Aljarafe 30/220 kV" y línea eléctrica 220 kV "SET FV Aljarafe-SET Santiponce", en Salteras y Valencina de la Concepción (Sevilla) y se declara, en concreto, la utilidad pública de la línea eléctrica de 220 kV "SET Aljarafe-SET Santiponce 220 kV".
Identificador: BOE-A-2023-21279
Título: Resolución de 3 de octubre de 2023, de la Dirección General de Política Energética y Minas, por la que se desestima la solicitud de Enel Green Power España, SL, de autorización administrativa previa del parque eólico Caaveiro, de 78 MW de potencia instalada, y de su infraestructura de evacuación, en la provincia de A Coruña.
Identificador: BOE-A-2023-22750
Título: Resolución de 26 de octubre de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SL, autorización administrativa previa y autorización administrativa de construcción para la instalación fotovoltaica Balbona, de 130,606 MW de potencia instalada, y su infraestructura de evacuación, en el término municipal de Jumilla (Murcia) y se declara, en concreto, la utilidad pública de la línea de evacuación a 132 kV «SET Balbona-SET La Alquería» y de la línea de evacuación a 400 kV «SET La Alquería-SET Peñarrubia REE».
Identificador: BOE-B-2023-35011
Título: Resolución de la Dirección General de Energía de 17 de octubre de 2023, por la que se concede a Enel Green Power España, S.L., Autorización Administrativa y Declaración, en concreto, de Utilidad Pública del Parque Fotovoltaico El Matorral, en el término municipal de San Bartolomé de Tirajana. Isla de Gran Canaria. Expediente ER201442.
Identificador: BOE-A-2023-25627
Título: Resolución de 5 de diciembre de 2023, de la Dirección General de Política Energética y Minas, por la que se otorga a Enel Green Power España, SLU, autorización administrativa de construcción para el módulo de generación denominado "Parque solar fotovoltaico Mudéjar", de 66 MW de potencia instalada, y su infraestructura de evacuación, consistente en las líneas de evacuación subterránea a 33 kV y la ampliación de la subestación ST02 220/33 kV con una nueva posición de entrada privativa en Andorra (Teruel) y se declara, en concreto, su utilidad pública.

In [39]:
# url_html
df_boe_23.loc[df_boe_23['identificador'] == 'BOE-A-2023-1', 'url_html'].values[0]

'https://www.boe.es/diario_boe/txt.php?id=BOE-A-2023-1'

In [103]:
regex

'alta tension|autorizacion administrativa de construccion|autorizacion administrativa previa|declaracion de impacto ambiental|energia eolica|energia solar|evacuacion de energia|evaluacion de impacto ambiental|expropiacion forzosa|generacion electrica|informacion publica|instalacion fotovoltaica|instalacion solar|linea de evacuacion|linea electrica|muy alta tension|ocupacion de bienes|parque eolico|parque solar|planta fotovoltaica|subestacion electrica|utilidad publica'

In [29]:
# pdf_link
df_boe_23.loc[df_boe_23['identificador'] == 'BOE-A-2023-1', 'pdf_link'].values[0]

'https://www.boe.es/boe/dias/2023/01/02/pdfs/BOE-A-2023-1.pdf'